sonar.projectKey=node-wire
sonar.projectName=Node Wire
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11

sonar.sources=src
sonar.tests=tests

sonar.exclusions=**/__pycache__/**,**/*.pyc,htmlcov/**,dist/**,playground/**,grafana/**
sonar.test.inclusions=tests/**/*.py

sonar.python.coverage.reportPaths=coverage.xml
