#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2026 AOT Technologies
# SPDX-License-Identifier: Apache-2.0
#
# Runs security, dependency, and open-source compliance checks.

set -e

cd "$(dirname "$0")/.."

echo "====================================="
echo "1. Generating DEPENDENCIES.md..."
echo "====================================="

cat << 'EOF' > DEPENDENCIES.md
# Node Wire Open Source Dependencies

This file is automatically generated and contains an inventory of all third-party dependencies used in the Node Wire project.

## License Classification Criteria
To maintain open-source compliance, dependencies are evaluated against the following criteria:
* **✅ Safe (Permissive):** MIT, Apache-2.0, BSD, PSF. These licenses are universally safe for our Apache 2.0 open-source release and can be freely used, modified, and distributed.
* **⚠️ Needs Review:** Custom or obscure licenses. These require manual review by the engineering team to ensure they don't impose conflicting obligations.
* **⛔ Risky (Copyleft):** GPLv2, GPLv3, AGPL. These licenses are strictly prohibited in the runtime application as they force derivative works to adopt the same open-source license. They may only be used as isolated, non-distributed Development/Linting tools.

---

EOF

uv run pip-licenses --format=markdown --with-urls >> DEPENDENCIES.md
echo "DEPENDENCIES.md generated successfully!"

echo ""
echo "====================================="
echo "2. Running Bandit (SAST Scanner)..."
echo "====================================="
# We allow medium/low severity but want to output findings.
uv run bandit -r src/ packages/ playground/ tests/ -ll || true

echo ""
echo "====================================="
echo "3. Running pip-audit (Vulnerability Scanner)..."
echo "====================================="
uv run pip-audit || true

echo ""
echo "Compliance checks finished!"
